import React, { use, useState, useEffect } from "react";
import Post from "./Post";

const NewsFeed = () => {
  return (
    <>
      <div>
        <Post
          subplace={"subplace"}
          username={"username"}
          time={"time"}
          questiontitle={"questiontitle"}
          questionbody={"questionbody"}
        />
        <Post
          subplace={"subplace"}
          username={"username"}
          time={"time"}
          questiontitle={"questiontitle"}
          questionbody={"questionbody"}
        />
        <Post
          subplace={"subplace"}
          username={"username"}
          time={"time"}
          questiontitle={"questiontitle"}
          questionbody={"questionbody"}
        />
        <Post
          subplace={"subplace"}
          username={"username"}
          time={"time"}
          questiontitle={"questiontitle"}
          questionbody={"questionbody"}
        />
        <Post
          subplace={"subplace"}
          username={"username"}
          time={"time"}
          questiontitle={"questiontitle"}
          questionbody={"questionbody"}
        />
        <Post
          subplace={"subplace"}
          username={"username"}
          time={"time"}
          questiontitle={"questiontitle"}
          questionbody={"questionbody"}
        />
        <Post
          subplace={"subplace"}
          username={"username"}
          time={"time"}
          questiontitle={"questiontitle"}
          questionbody={"questionbody"}
        />
        <Post
          subplace={"subplace"}
          username={"username"}
          time={"time"}
          questiontitle={"questiontitle"}
          questionbody={"questionbody"}
        />
        <Post
          subplace={"subplace"}
          username={"username"}
          time={"time"}
          questiontitle={"questiontitle"}
          questionbody={"questionbody"}
        />
        <Post
          subplace={"subplace"}
          username={"username"}
          time={"time"}
          questiontitle={"questiontitle"}
          questionbody={"questionbody"}
        />
        <Post
          subplace={"subplace"}
          username={"username"}
          time={"time"}
          questiontitle={"questiontitle"}
          questionbody={"questionbody"}
        />
        <Post
          subplace={"subplace"}
          username={"username"}
          time={"time"}
          questiontitle={"questiontitle"}
          questionbody={"questionbody"}
        />
      </div>
    </>
  );
};

export default NewsFeed;
